language: generic
udo: required
services:
  - docker

before_install:
  - docker build -t mikecigaw/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikecigaw/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-711681966202"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
    