language: generic
udo: required
services:
  - docker

before_install:
  - docker build -t mikecigaw/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikecigaw/docker-react npm run test